# fly.toml - Cấu hình cho Fly.io deployment
app = "odoo-app"
primary_region = "sin"  # Singapore

[build]

[env]
  PORT = "8069"

[http_service]
  internal_port = 8069
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/opt/odoo/odoo/addons/web/static"
  url_prefix = "/web/static"
